In [1]:
!pip install optuna

Requirement already satisfied: optuna in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: tomli in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from alembic>=1.5.0->optuna) (2.4.1)
Requirement already satisfied: greenlet>=1 in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: colorama in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\acer\downloads\cancer-risk-prediction-complete_1\.venv\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [2]:
# Importing the libraries

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [3]:
# Prepare your data
from pathlib import Path

# Works in VS Code/local project; fallback keeps compatibility if path differs.
data_path = Path('data/cancer-risk-factors.csv')
if not data_path.exists():
    data_path = Path('../data/cancer-risk-factors.csv')

df = pd.read_csv(data_path)
print(f"Loaded dataset from: {data_path.resolve()}")
print(f"Shape: {df.shape}")

Loaded dataset from: C:\Users\Acer\Downloads\Cancer-Risk-Prediction-Complete_1\data\cancer-risk-factors.csv
Shape: (2000, 21)

In [4]:
df.head(5)

,Patient_ID,Cancer_Type,Age,Gender,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,...,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level,Risk_Level
0,LU0000,Breast,68,0,7,2,8,0,5,3,...,4,6,3,1,0,0,0.398696,28.0,5,Medium
1,LU0001,Prostate,74,1,8,9,8,0,0,3,...,1,3,3,0,0,5,0.424299,25.4,9,Medium
2,LU0002,Skin,55,1,7,10,7,0,3,3,...,1,8,10,0,0,6,0.605082,28.6,2,Medium
3,LU0003,Colon,61,0,6,2,2,0,6,2,...,6,4,8,0,0,8,0.318449,32.1,7,Low
4,LU0004,Lung,67,1,10,7,4,0,6,3,...,9,10,9,0,0,5,0.524358,25.1,2,Medium

In [5]:
X = df.drop(columns=['Risk_Level','Patient_ID', 'Cancer_Type'])

# Encode the target variable
le = LabelEncoder()
y = le.fit_transform(df['Risk_Level'])

In [6]:
X

,Age,Gender,Smoking,Alcohol_Use,Obesity,Family_History,Diet_Red_Meat,Diet_Salted_Processed,Fruit_Veg_Intake,Physical_Activity,Air_Pollution,Occupational_Hazards,BRCA_Mutation,H_Pylori_Infection,Calcium_Intake,Overall_Risk_Score,BMI,Physical_Activity_Level
0,68,0,7,2,8,0,5,3,7,4,6,3,1,0,0,0.398696,28.0,5
1,74,1,8,9,8,0,0,3,7,1,3,3,0,0,5,0.424299,25.4,9
2,55,1,7,10,7,0,3,3,4,1,8,10,0,0,6,0.605082,28.6,2
3,61,0,6,2,2,0,6,2,4,6,4,8,0,0,8,0.318449,32.1,7
4,67,1,10,7,4,0,6,3,10,9,10,9,0,0,5,0.524358,25.1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,60,1,4,6,4,0,10,6,4,4,5,3,1,0,4,0.437539,30.3,3
1996,84,1,5,7,8,0,10,0,1,2,1,3,0,0,2,0.451128,25.9,4
1997,65,0,7,2,10,0,4,2,2,3,6,0,0,1,0,0.295760,22.5,3
1998,64,1,10,2,10,0,2,10,7,5,4,2,0,0,10,0.422201,25.3,3
1999,64,0,3,4,10,0,0,5,1,0,3,9,0,0,0,0.518137,23.0,3

In [7]:
y

array([2, 2, 2, ..., 1, 2, 2])

## why cancer_type was removed from the features list

- It's not a predictive input - it's an outcome label or categorical grouping that's already strongly correlated with Risk Level

- If we include it, the model will cheat by learning the mapping like Prostate --> High risk, instead of learning from true risk factors (smoking, BMI etc)

In [8]:
# Split into training/test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)

In [9]:
# Feature Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
model = RandomForestClassifier(random_state=42, n_estimators=100)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [11]:
y_pred = model.predict(X_test)

print("Classification Report")
print(classification_report(y_test, y_pred, target_names=le.classes_))

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

        High       1.00      0.95      0.97        20
         Low       1.00      1.00      1.00        65
      Medium       1.00      1.00      1.00       315

    accuracy                           1.00       400
   macro avg       1.00      0.98      0.99       400
weighted avg       1.00      1.00      1.00       400

Confusion Matrix
[[ 19   0   1]
 [  0  65   0]
 [  0   0 315]]

The model accurately distinguishes all risk levels, with only 1 mistake out of 400 with imbalanced dataset.

## Logistic Regression

In [12]:
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [13]:
y_pred_lr = log_reg.predict(X_test)

print("Classification Report")
print(classification_report(y_test, y_pred_lr, target_names=le.classes_))

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_lr))

Classification Report
              precision    recall  f1-score   support

        High       1.00      0.80      0.89        20
         Low       0.97      0.95      0.96        65
      Medium       0.98      0.99      0.99       315

    accuracy                           0.98       400
   macro avg       0.98      0.92      0.95       400
weighted avg       0.98      0.98      0.98       400

Confusion Matrix
[[ 16   0   4]
 [  0  62   3]
 [  0   2 313]]

## Removing Overall_Risk_Score and retrying

In [14]:
X_new = df.drop(columns=['Risk_Level','Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])

# Encode the target variable
le_new = LabelEncoder()
y_new = le_new.fit_transform(df['Risk_Level'])

In [15]:
# Split into training/test

X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size = 0.2, random_state=42, stratify=y)

In [16]:
# Feature Scaling

scaler_new = StandardScaler()
X_train_new = scaler_new.fit_transform(X_train_new)
X_test_new = scaler_new.transform(X_test_new)

In [17]:
model_new = RandomForestClassifier(random_state=42, n_estimators=100)
model_new.fit(X_train_new, y_train_new)

RandomForestClassifier(random_state=42)

In [18]:
y_pred_new = model_new.predict(X_test_new)

print("Classification Report")
print(classification_report(y_test_new, y_pred_new, target_names=le.classes_))

print("Confusion Matrix")
print(confusion_matrix(y_test_new, y_pred_new))

Classification Report
              precision    recall  f1-score   support

        High       1.00      0.05      0.10        20
         Low       0.85      0.34      0.48        65
      Medium       0.83      0.99      0.90       315

    accuracy                           0.83       400
   macro avg       0.89      0.46      0.49       400
weighted avg       0.84      0.83      0.80       400

Confusion Matrix
[[  1   0  19]
 [  0  22  43]
 [  0   4 311]]

In [19]:
df.Risk_Level.value_counts()

Risk_Level
Medium    1574
Low        324
High       102
Name: count, dtype: int64

## SMOTE - Synthetic Minority Over-Sampling Technique

In [20]:
X = df.drop(columns=['Risk_Level','Patient_ID', 'Cancer_Type', 'Overall_Risk_Score'])
y = df['Risk_Level']

In [21]:
# Split into training/test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42, stratify=y)

In [22]:
from imblearn.over_sampling import SMOTE

In [23]:
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train,y_train)

print("Class Distribution")
print(y_train_res.value_counts())

Class Distribution
Risk_Level
Medium    1259
Low       1259
High      1259
Name: count, dtype: int64

In [24]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_res, y_train_res)

RandomForestClassifier(random_state=42)

In [25]:
y_pred = rf_model.predict(X_test)

print("Classification Report")
print(classification_report(y_test, y_pred))

print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))

Classification Report
              precision    recall  f1-score   support

        High       0.41      0.35      0.38        20
         Low       0.73      0.58      0.65        65
      Medium       0.88      0.92      0.90       315

    accuracy                           0.84       400
   macro avg       0.67      0.62      0.64       400
weighted avg       0.83      0.84      0.83       400

Confusion Matrix
[[  7   0  13]
 [  0  38  27]
 [ 10  14 291]]

- Accuracy: 84%
- High Risk: 7 correctly classified, 13 mis-classified as Medium
- Low Risk: 38 correctly classified, 27 confused with Medium
- Medium Risk: 291 correctly classified, 24 confused as High/Low

- Still struggles to detect High-risk patients even with SMOTE

## Optuna Tuning

In [26]:
# Optuna tuning
import optuna
from optuna.samplers import TPESampler
from sklearn.metrics import classification_report, confusion_matrix, make_scorer, f1_score
from sklearn.model_selection import StratifiedKFold, cross_val_score

import numpy as np
import joblib  # optional, to save model/study

c:\Users\Acer\Downloads\Cancer-Risk-Prediction-Complete_1\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [27]:
X_train_res.shape

(3777, 17)

In [28]:
from sklearn.metrics import f1_score, make_scorer

# Define macro F1 scorer explicitly for multiclass
def macro_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='macro')

scorer = make_scorer(macro_f1)

In [29]:
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'entropy']),
        'random_state': 42,
        'n_jobs': -1
    }

    model = RandomForestClassifier(**params)

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in cv.split(X_train_res, y_train_res):
        X_t, X_v = X_train_res.iloc[train_idx], X_train_res.iloc[val_idx]
        y_t, y_v = y_train_res.iloc[train_idx], y_train_res.iloc[val_idx]

        model.fit(X_t, y_t)
        y_pred = model.predict(X_v)

        score = f1_score(y_v, y_pred, average='macro')  # explicit multiclass handling
        scores.append(score)

    return np.mean(scores)

In [30]:
# --- Create study ---
sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='rf_macro_f1')

[I 2026-04-09 23:24:30,384] A new study created in memory with name: rf_macro_f1

In [31]:
# --- Run optimization ---
n_trials = 50  # change to 100+ if you want more thorough search
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

print("Best trial:")
print("  Value (macro F1):", study.best_value)
print("  Params:")
for k, v in study.best_params.items():
    print(f"    {k}: {v}")

Best trial: 0. Best value: 0.940236:   2%|▏         | 1/50 [00:02<01:57,  2.39s/it]

[I 2026-04-09 23:24:38,481] Trial 0 finished with value: 0.9402356457892479 and parameters: {'n_estimators': 218, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 0 with value: 0.9402356457892479.

Best trial: 1. Best value: 0.948868:   4%|▍         | 2/50 [00:03<01:06,  1.39s/it]

[I 2026-04-09 23:24:39,147] Trial 1 finished with value: 0.9488676606640238 and parameters: {'n_estimators': 59, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 1. Best value: 0.948868:   6%|▌         | 3/50 [00:05<01:27,  1.86s/it]

[I 2026-04-09 23:24:41,588] Trial 2 finished with value: 0.9045887437906642 and parameters: {'n_estimators': 325, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 1. Best value: 0.948868:   8%|▊         | 4/50 [00:08<01:41,  2.21s/it]

[I 2026-04-09 23:24:44,326] Trial 3 finished with value: 0.9089885645353499 and parameters: {'n_estimators': 324, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 1. Best value: 0.948868:  10%|█         | 5/50 [00:09<01:19,  1.76s/it]

[I 2026-04-09 23:24:45,296] Trial 4 finished with value: 0.9266627124403138 and parameters: {'n_estimators': 105, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 1. Best value: 0.948868:  12%|█▏        | 6/50 [00:13<02:01,  2.76s/it]

[I 2026-04-09 23:24:49,974] Trial 5 finished with value: 0.9319302481500912 and parameters: {'n_estimators': 487, 'max_depth': 24, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 1. Best value: 0.948868:  14%|█▍        | 7/50 [00:16<01:50,  2.56s/it]

[I 2026-04-09 23:24:52,145] Trial 6 finished with value: 0.9427963195232238 and parameters: {'n_estimators': 225, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 1. Best value: 0.948868:  16%|█▌        | 8/50 [00:19<01:57,  2.81s/it]

[I 2026-04-09 23:24:55,480] Trial 7 finished with value: 0.9123217127530691 and parameters: {'n_estimators': 398, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 1 with value: 0.9488676606640238.

Best trial: 8. Best value: 0.953646:  18%|█▊        | 9/50 [00:23<02:08,  3.14s/it]

[I 2026-04-09 23:24:59,331] Trial 8 finished with value: 0.9536461969280231 and parameters: {'n_estimators': 439, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9536461969280231.

Best trial: 8. Best value: 0.953646:  20%|██        | 10/50 [00:24<01:42,  2.56s/it]

[I 2026-04-09 23:25:00,616] Trial 9 finished with value: 0.9302234411015569 and parameters: {'n_estimators': 103, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 8 with value: 0.9536461969280231.

Best trial: 8. Best value: 0.953646:  22%|██▏       | 11/50 [00:29<02:08,  3.29s/it]

[I 2026-04-09 23:25:05,565] Trial 10 finished with value: 0.9531388022489152 and parameters: {'n_estimators': 491, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 8 with value: 0.9536461969280231.

Best trial: 11. Best value: 0.953651:  24%|██▍       | 12/50 [00:33<02:16,  3.59s/it]

[I 2026-04-09 23:25:09,827] Trial 11 finished with value: 0.9536505757542448 and parameters: {'n_estimators': 492, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  26%|██▌       | 13/50 [00:37<02:14,  3.63s/it]

[I 2026-04-09 23:25:13,561] Trial 12 finished with value: 0.9523684290837874 and parameters: {'n_estimators': 411, 'max_depth': 21, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  28%|██▊       | 14/50 [00:41<02:15,  3.75s/it]

[I 2026-04-09 23:25:17,577] Trial 13 finished with value: 0.9487926962406048 and parameters: {'n_estimators': 427, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  30%|███       | 15/50 [00:46<02:21,  4.05s/it]

[I 2026-04-09 23:25:22,314] Trial 14 finished with value: 0.944250057888667 and parameters: {'n_estimators': 496, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  32%|███▏      | 16/50 [00:48<02:03,  3.62s/it]

[I 2026-04-09 23:25:24,959] Trial 15 finished with value: 0.8013295571346774 and parameters: {'n_estimators': 359, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  34%|███▍      | 17/50 [00:53<02:04,  3.79s/it]

[I 2026-04-09 23:25:29,128] Trial 16 finished with value: 0.9332015562379373 and parameters: {'n_estimators': 447, 'max_depth': 25, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  36%|███▌      | 18/50 [00:55<01:49,  3.41s/it]

[I 2026-04-09 23:25:31,675] Trial 17 finished with value: 0.9271178985364245 and parameters: {'n_estimators': 252, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  38%|███▊      | 19/50 [00:59<01:48,  3.50s/it]

[I 2026-04-09 23:25:35,378] Trial 18 finished with value: 0.9463419377951339 and parameters: {'n_estimators': 358, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  40%|████      | 20/50 [01:03<01:54,  3.82s/it]

[I 2026-04-09 23:25:39,924] Trial 19 finished with value: 0.9465878359354778 and parameters: {'n_estimators': 456, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 11. Best value: 0.953651:  42%|████▏     | 21/50 [01:05<01:33,  3.22s/it]

[I 2026-04-09 23:25:41,741] Trial 20 finished with value: 0.9450207220267989 and parameters: {'n_estimators': 165, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 11 with value: 0.9536505757542448.

Best trial: 21. Best value: 0.953677:  44%|████▍     | 22/50 [01:10<01:46,  3.79s/it]

[I 2026-04-09 23:25:46,872] Trial 21 finished with value: 0.953676796405608 and parameters: {'n_estimators': 497, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  46%|████▌     | 23/50 [01:14<01:45,  3.90s/it]

[I 2026-04-09 23:25:51,055] Trial 22 finished with value: 0.9528819219414548 and parameters: {'n_estimators': 452, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  48%|████▊     | 24/50 [01:18<01:38,  3.78s/it]

[I 2026-04-09 23:25:54,541] Trial 23 finished with value: 0.9460575848167427 and parameters: {'n_estimators': 375, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  50%|█████     | 25/50 [01:22<01:36,  3.86s/it]

[I 2026-04-09 23:25:58,595] Trial 24 finished with value: 0.9396532066839051 and parameters: {'n_estimators': 467, 'max_depth': 24, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  52%|█████▏    | 26/50 [01:25<01:25,  3.55s/it]

[I 2026-04-09 23:26:01,398] Trial 25 finished with value: 0.9528460941726316 and parameters: {'n_estimators': 310, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  54%|█████▍    | 27/50 [01:29<01:24,  3.68s/it]

[I 2026-04-09 23:26:05,403] Trial 26 finished with value: 0.9465852439374097 and parameters: {'n_estimators': 421, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  56%|█████▌    | 28/50 [01:33<01:25,  3.89s/it]

[I 2026-04-09 23:26:09,770] Trial 27 finished with value: 0.9442367777739015 and parameters: {'n_estimators': 498, 'max_depth': 26, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  58%|█████▊    | 29/50 [01:37<01:18,  3.74s/it]

[I 2026-04-09 23:26:13,167] Trial 28 finished with value: 0.949926701377977 and parameters: {'n_estimators': 391, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  60%|██████    | 30/50 [01:39<01:08,  3.44s/it]

[I 2026-04-09 23:26:15,905] Trial 29 finished with value: 0.9369943481182208 and parameters: {'n_estimators': 289, 'max_depth': 28, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 21. Best value: 0.953677:  62%|██████▏   | 31/50 [01:44<01:10,  3.70s/it]

[I 2026-04-09 23:26:20,221] Trial 30 finished with value: 0.9331872547809418 and parameters: {'n_estimators': 445, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 21 with value: 0.953676796405608.

Best trial: 31. Best value: 0.953933:  64%|██████▍   | 32/50 [01:48<01:10,  3.91s/it]

[I 2026-04-09 23:26:24,589] Trial 31 finished with value: 0.9539329186205472 and parameters: {'n_estimators': 476, 'max_depth': 15, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 31. Best value: 0.953933:  66%|██████▌   | 33/50 [01:53<01:10,  4.16s/it]

[I 2026-04-09 23:26:29,355] Trial 32 finished with value: 0.9485232703292462 and parameters: {'n_estimators': 466, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 31. Best value: 0.953933:  68%|██████▊   | 34/50 [01:57<01:05,  4.09s/it]

[I 2026-04-09 23:26:33,289] Trial 33 finished with value: 0.9408829490644962 and parameters: {'n_estimators': 430, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 31. Best value: 0.953933:  70%|███████   | 35/50 [02:01<01:02,  4.14s/it]

[I 2026-04-09 23:26:37,521] Trial 34 finished with value: 0.953748576314346 and parameters: {'n_estimators': 473, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 31. Best value: 0.953933:  72%|███████▏  | 36/50 [02:05<00:57,  4.10s/it]

[I 2026-04-09 23:26:41,516] Trial 35 finished with value: 0.953692579953389 and parameters: {'n_estimators': 470, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 31. Best value: 0.953933:  74%|███████▍  | 37/50 [02:09<00:53,  4.12s/it]

[I 2026-04-09 23:26:45,699] Trial 36 finished with value: 0.9528844027409092 and parameters: {'n_estimators': 468, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 31. Best value: 0.953933:  76%|███████▌  | 38/50 [02:13<00:46,  3.90s/it]

[I 2026-04-09 23:26:49,088] Trial 37 finished with value: 0.9431504208584275 and parameters: {'n_estimators': 349, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 31 with value: 0.9539329186205472.

Best trial: 38. Best value: 0.955532:  78%|███████▊  | 39/50 [02:16<00:42,  3.85s/it]

[I 2026-04-09 23:26:52,840] Trial 38 finished with value: 0.9555317075973213 and parameters: {'n_estimators': 396, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 38 with value: 0.9555317075973213.

Best trial: 38. Best value: 0.955532:  80%|████████  | 40/50 [02:19<00:36,  3.64s/it]

[I 2026-04-09 23:26:55,997] Trial 39 finished with value: 0.935654412766623 and parameters: {'n_estimators': 384, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 38 with value: 0.9555317075973213.

Best trial: 38. Best value: 0.955532:  82%|████████▏ | 41/50 [02:23<00:33,  3.67s/it]

[I 2026-04-09 23:26:59,713] Trial 40 finished with value: 0.9453305006869693 and parameters: {'n_estimators': 413, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 38 with value: 0.9555317075973213.

Best trial: 41. Best value: 0.956072:  84%|████████▍ | 42/50 [02:28<00:31,  3.93s/it]

[I 2026-04-09 23:27:04,261] Trial 41 finished with value: 0.9560722551368168 and parameters: {'n_estimators': 472, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  86%|████████▌ | 43/50 [02:32<00:28,  4.06s/it]

[I 2026-04-09 23:27:08,629] Trial 42 finished with value: 0.9560667999664281 and parameters: {'n_estimators': 471, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  88%|████████▊ | 44/50 [02:37<00:25,  4.18s/it]

[I 2026-04-09 23:27:13,086] Trial 43 finished with value: 0.9552672807679888 and parameters: {'n_estimators': 472, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  90%|█████████ | 45/50 [02:41<00:20,  4.20s/it]

[I 2026-04-09 23:27:17,328] Trial 44 finished with value: 0.9525651846147007 and parameters: {'n_estimators': 404, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  92%|█████████▏| 46/50 [02:45<00:17,  4.28s/it]

[I 2026-04-09 23:27:21,800] Trial 45 finished with value: 0.9520772165021881 and parameters: {'n_estimators': 436, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  94%|█████████▍| 47/50 [02:47<00:10,  3.56s/it]

[I 2026-04-09 23:27:23,680] Trial 46 finished with value: 0.9520633123780685 and parameters: {'n_estimators': 174, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  96%|█████████▌| 48/50 [02:50<00:07,  3.50s/it]

[I 2026-04-09 23:27:27,044] Trial 47 finished with value: 0.9528554570488716 and parameters: {'n_estimators': 321, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072:  98%|█████████▊| 49/50 [02:55<00:03,  3.76s/it]

[I 2026-04-09 23:27:31,415] Trial 48 finished with value: 0.9442650744438706 and parameters: {'n_estimators': 480, 'max_depth': 22, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.

Best trial: 41. Best value: 0.956072: 100%|██████████| 50/50 [02:58<00:00,  3.58s/it]

[I 2026-04-09 23:27:34,999] Trial 49 finished with value: 0.937829367661044 and parameters: {'n_estimators': 404, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 41 with value: 0.9560722551368168.
Best trial:
  Value (macro F1): 0.9560722551368168
  Params:
    n_estimators: 472
    max_depth: 15
    min_samples_split: 6
    min_samples_leaf: 2
    max_features: sqrt
    bootstrap: False
    criterion: entropy

In [32]:
# Train final model with best params and full training data, then evaluate on test
best_params = {
    'n_estimators': 347,
    'max_depth': 19,
    'min_samples_split': 2,
    'min_samples_leaf': 1,
    'max_features': 'sqrt',
    'bootstrap': False,
    'criterion': 'gini',
    'random_state': 42,
    'n_jobs': -1
}


final_rf = RandomForestClassifier(**best_params)
final_rf.fit(X_train_res, y_train_res)         # resampled training set
y_pred_test = final_rf.predict(X_test)        # untouched test set

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_test))
print(confusion_matrix(y_test, y_pred_test))

              precision    recall  f1-score   support

        High       0.36      0.25      0.29        20
         Low       0.72      0.58      0.64        65
      Medium       0.87      0.92      0.90       315

    accuracy                           0.83       400
   macro avg       0.65      0.59      0.61       400
weighted avg       0.82      0.83      0.83       400

[[  5   0  15]
 [  0  38  27]
 [  9  15 291]]

In [33]:
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import f1_score, make_scorer, recall_score
import optuna
import numpy as np

# scorer (macro f1)
def macro_f1(y_true, y_pred):
    return f1_score(y_true, y_pred, average='macro')

macro_f1_scorer = make_scorer(macro_f1)

def objective(trial):
    # RF params to try
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 400),
        'max_depth': trial.suggest_int('max_depth', 6, 20),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 8),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 6),
        'max_features': trial.suggest_categorical('max_features', ['sqrt','log2']),
        'bootstrap': trial.suggest_categorical('bootstrap', [True, False]),
        'criterion': trial.suggest_categorical('criterion', ['gini','entropy']),
        'random_state': 42,
        'n_jobs': 1   # avoid nested parallelism inside cross_val_score
    }

    sm = SMOTE(random_state=42)
    rf = RandomForestClassifier(**params)
    pipe = ImbPipeline([('smote', sm), ('rf', rf)])

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = cross_val_score(pipe, X_train, y_train, cv=cv, scoring=macro_f1_scorer, n_jobs=1)
    return float(np.mean(scores))

study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=30)
print(study.best_value, study.best_params)

[I 2026-04-09 23:27:58,767] A new study created in memory with name: no-name-0fbe8546-1a36-4829-ab4d-33ee9dce57b7
[I 2026-04-09 23:28:03,176] Trial 0 finished with value: 0.671473898202647 and parameters: {'n_estimators': 212, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 0 with value: 0.671473898202647.
[I 2026-04-09 23:28:05,152] Trial 1 finished with value: 0.6657242146375855 and parameters: {'n_estimators': 106, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 0 with value: 0.671473898202647.
[I 2026-04-09 23:28:09,287] Trial 2 finished with value: 0.6616028068735651 and parameters: {'n_estimators': 284, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 0 with value: 0.671473898202647.
[I 2026-04-09 23:28:12,722] Trial 3 finished with value: 0.6822470358393412 and parameters: {'n_estimators': 282, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 3 with value: 0.6822470358393412.
[I 2026-04-09 23:28:14,991] Trial 4 finished with value: 0.6843940052187558 and parameters: {'n_estimators': 136, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'gini'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-04-09 23:28:22,137] Trial 5 finished with value: 0.6766106997681756 and parameters: {'n_estimators': 391, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-04-09 23:28:25,973] Trial 6 finished with value: 0.6736420648931846 and parameters: {'n_estimators': 216, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-04-09 23:28:29,936] Trial 7 finished with value: 0.6740912674902791 and parameters: {'n_estimators': 332, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-04-09 23:28:35,182] Trial 8 finished with value: 0.6725157701607243 and parameters: {'n_estimators': 359, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'criterion': 'gini'}. Best is trial 4 with value: 0.6843940052187558.
[I 2026-04-09 23:28:37,170] Trial 9 finished with value: 0.6844259490685912 and parameters: {'n_estimators': 135, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 9 with value: 0.6844259490685912.
[I 2026-04-09 23:28:40,519] Trial 10 finished with value: 0.6812802260326801 and parameters: {'n_estimators': 162, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 9 with value: 0.6844259490685912.
[I 2026-04-09 23:28:42,109] Trial 11 finished with value: 0.6879525784535884 and parameters: {'n_estimators': 103, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6879525784535884.
[I 2026-04-09 23:28:43,488] Trial 12 finished with value: 0.6875150286235802 and parameters: {'n_estimators': 105, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6879525784535884.
[I 2026-04-09 23:28:46,113] Trial 13 finished with value: 0.6871336394307516 and parameters: {'n_estimators': 183, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 11 with value: 0.6879525784535884.
[I 2026-04-09 23:28:47,918] Trial 14 finished with value: 0.696319735673656 and parameters: {'n_estimators': 123, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:28:50,583] Trial 15 finished with value: 0.6825703383865873 and parameters: {'n_estimators': 178, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:28:53,848] Trial 16 finished with value: 0.6916259354121096 and parameters: {'n_estimators': 238, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:28:57,296] Trial 17 finished with value: 0.6916126044960872 and parameters: {'n_estimators': 256, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:01,780] Trial 18 finished with value: 0.6870455010447746 and parameters: {'n_estimators': 315, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:04,698] Trial 19 finished with value: 0.6463935009243947 and parameters: {'n_estimators': 218, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:09,173] Trial 20 finished with value: 0.68817874851555 and parameters: {'n_estimators': 265, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:12,734] Trial 21 finished with value: 0.6928436553163899 and parameters: {'n_estimators': 236, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:15,894] Trial 22 finished with value: 0.6909281053018201 and parameters: {'n_estimators': 229, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:19,811] Trial 23 finished with value: 0.6918893385313901 and parameters: {'n_estimators': 239, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:24,910] Trial 24 finished with value: 0.6925265325563879 and parameters: {'n_estimators': 301, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:30,583] Trial 25 finished with value: 0.6784822731209473 and parameters: {'n_estimators': 319, 'max_depth': 19, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:35,192] Trial 26 finished with value: 0.6922979486592911 and parameters: {'n_estimators': 296, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:40,124] Trial 27 finished with value: 0.6896597276003851 and parameters: {'n_estimators': 359, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:43,113] Trial 28 finished with value: 0.6899195109112785 and parameters: {'n_estimators': 196, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.
[I 2026-04-09 23:29:45,928] Trial 29 finished with value: 0.6784423939550094 and parameters: {'n_estimators': 149, 'max_depth': 19, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy'}. Best is trial 14 with value: 0.696319735673656.

0.696319735673656 {'n_estimators': 123, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy'}

In [34]:
# Suppose best_params from study:
best = study.best_params
rf = RandomForestClassifier(**best, random_state=42, n_jobs=-1)

pipe_final = ImbPipeline([('smote', SMOTE(random_state=42)), ('rf', rf)])
pipe_final.fit(X_train, y_train)   # fit on original X_train (pipeline will SMOTE inside)

y_test_pred = pipe_final.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

              precision    recall  f1-score   support

        High       0.33      0.40      0.36        20
         Low       0.70      0.62      0.66        65
      Medium       0.88      0.90      0.89       315

    accuracy                           0.82       400
   macro avg       0.64      0.64      0.64       400
weighted avg       0.83      0.82      0.83       400

[[  8   0  12]
 [  0  40  25]
 [ 16  17 282]]

## **XGBoost**

In [36]:
# baseline XGBoost (SMOTE on training split only)

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

le = LabelEncoder()
le.fit(y_train)

y_train_enc = le.transform(y_train)
y_test_enc = le.transform(y_test)

xgb = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42, n_jobs=-1)
smote = SMOTE(random_state=42)

X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train_enc)
xgb.fit(X_train_bal, y_train_bal)

y_pred_enc = xgb.predict(X_test)

y_pred = le.inverse_transform(y_pred_enc)
y_test_orig = le.inverse_transform(y_test_enc)

print("Baseline XGB Classifier")
print(classification_report(y_test_orig, y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test_orig, y_pred))

Baseline XGB Classifier
              precision    recall  f1-score   support

        High       0.39      0.45      0.42        20
         Low       0.79      0.68      0.73        65
      Medium       0.90      0.92      0.91       315

    accuracy                           0.85       400
   macro avg       0.69      0.68      0.68       400
weighted avg       0.86      0.85      0.85       400

Confusion Matrix
[[  9   0  11]
 [  0  44  21]
 [ 14  12 289]]

In [37]:
## Optuna + XGBoost that optimizes recall for the High class (SMOTE applied inside each fold).

# --- Imports ---
import optuna
from optuna.samplers import TPESampler
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import recall_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# --- Settings ---
TARGET_LABEL = 'High'       # label whose recall we want to maximize
LABEL_ORDER = ['High', 'Low', 'Medium']  # must match your label names exactly
N_TRIALS = 40               # start with 40; increase to 100+ for more thorough search
CV_FOLDS = 3

# --- Encode labels once (keep mapping stable) ---
le = LabelEncoder()
le.fit(y_train)               # fit on training labels (or whole y if preferred)
y_train_enc = le.transform(y_train)
y_test_enc  = le.transform(y_test)
# numeric index of target label in encoded space
target_index = int(np.where(le.classes_ == TARGET_LABEL)[0])

# --- Objective: maximize recall for TARGET_LABEL ---
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 400),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 5.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        # stable args
        'random_state': 42,
        'use_label_encoder': False,
        'eval_metric': 'mlogloss'
    }

    cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=42)
    recalls = []

    for train_idx, val_idx in cv.split(X_train, y_train_enc):
        X_t, X_v = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_t, y_v = y_train_enc[train_idx], y_train_enc[val_idx]

        # Apply SMOTE only on the fold's training subset.
        smote = SMOTE(random_state=42)
        X_t_bal, y_t_bal = smote.fit_resample(X_t, y_t)

        # n_jobs=1 to avoid nested parallelism inside CV
        model = XGBClassifier(**params, n_jobs=1)
        model.fit(X_t_bal, y_t_bal)
        y_pred = model.predict(X_v)

        # compute recall per class in LABEL_ORDER and select target_index
        recs = recall_score(y_v, y_pred, labels=list(range(len(le.classes_))), average=None, zero_division=0)
        recall_high = recs[target_index]
        recalls.append(recall_high)

    return float(np.mean(recalls))

# --- Run Optuna study ---
sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='xgb_high_recall')
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print("\nBest CV mean High-recall:", study.best_value)
print("Best params:")
for k,v in study.best_params.items():
    print(f"  {k}: {v}")

# --- Train final model with best params and evaluate on test set ---
best_params = study.best_params.copy()
# ensure required fixed args for final fit
best_params.update({'use_label_encoder': False, 'eval_metric': 'mlogloss', 'random_state': 42})
final_xgb = XGBClassifier(**best_params, n_jobs=-1)

# Fit SMOTE only on training data, then train XGB.
smote_final = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote_final.fit_resample(X_train, y_train_enc)
final_xgb.fit(X_train_bal, y_train_bal)

# predict (encoded), then decode for readable report
y_test_pred_enc = final_xgb.predict(X_test)
y_test_pred = le.inverse_transform(y_test_pred_enc)
y_test_orig = y_test  # original readable labels

print("\nFINAL Test Classification Report (labels in original names):")
print(classification_report(y_test_orig, y_test_pred, labels=le.classes_))
print("Confusion Matrix (rows=true, cols=predicted, order = le.classes_):")
print(confusion_matrix(y_test_orig, y_test_pred, labels=le.classes_))

C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  target_index = int(np.where(le.classes_ == TARGET_LABEL)[0])
[I 2026-04-09 23:31:15,234] A new study created in memory with name: xgb_high_recall
  0%|          | 0/40 [00:00<?, ?it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
Best trial: 0. Best value: 0.489418:   2%|▎         | 1/40 [00:01<00:53,  1.38s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:16,616] Trial 0 finished with value: 0.4894179894179895 and parameters: {'n_estimators': 181, 'max_depth': 12, 'learning_rate': 0.1205712628744377, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.4936111842654619, 'gamma': 0.7799726016810132, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: 0.4894179894179895.

Best trial: 0. Best value: 0.489418:   5%|▌         | 2/40 [00:05<01:54,  3.01s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:20,764] Trial 1 finished with value: 0.4532627865961199 and parameters: {'n_estimators': 260, 'max_depth': 10, 'learning_rate': 0.010725209743171996, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.899465584480253, 'gamma': 1.0616955533913808, 'reg_alpha': 0.9091248360355031, 'reg_lambda': 0.9170225492671691}. Best is trial 0 with value: 0.4894179894179895.

Best trial: 2. Best value: 0.502646:   8%|▊         | 3/40 [00:07<01:31,  2.47s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:22,581] Trial 2 finished with value: 0.5026455026455027 and parameters: {'n_estimators': 156, 'max_depth': 8, 'learning_rate': 0.04345454109729477, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.7671117368334277, 'gamma': 0.6974693032602092, 'reg_alpha': 1.4607232426760908, 'reg_lambda': 1.8318092164684585}. Best is trial 2 with value: 0.5026455026455027.

Best trial: 2. Best value: 0.502646:  10%|█         | 4/40 [00:10<01:35,  2.66s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:25,548] Trial 3 finished with value: 0.5026455026455027 and parameters: {'n_estimators': 210, 'max_depth': 10, 'learning_rate': 0.019721610970574007, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 3.0377242595071916, 'reg_lambda': 0.8526206184364576}. Best is trial 2 with value: 0.5026455026455027.

Best trial: 2. Best value: 0.502646:  12%|█▎        | 5/40 [00:10<01:07,  1.93s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:26,194] Trial 4 finished with value: 0.4775132275132275 and parameters: {'n_estimators': 72, 'max_depth': 12, 'learning_rate': 0.26690431824362526, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.5827682615040224, 'gamma': 0.48836057003191935, 'reg_alpha': 3.4211651325607844, 'reg_lambda': 2.2007624686980067}. Best is trial 2 with value: 0.5026455026455027.

Best trial: 2. Best value: 0.502646:  15%|█▌        | 6/40 [00:11<00:54,  1.59s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:27,119] Trial 5 finished with value: 0.4898589065255732 and parameters: {'n_estimators': 92, 'max_depth': 7, 'learning_rate': 0.011240768803005551, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.5552679889600102, 'gamma': 3.31261142176991, 'reg_alpha': 1.5585553804470549, 'reg_lambda': 2.600340105889054}. Best is trial 2 with value: 0.5026455026455027.

Best trial: 6. Best value: 0.611552:  18%|█▊        | 7/40 [00:13<00:50,  1.54s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:28,549] Trial 6 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.27051668818999286, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9636993649385135, 'gamma': 4.474136752138244, 'reg_alpha': 2.9894998940554256, 'reg_lambda': 4.609371175115584}. Best is trial 6 with value: 0.6115520282186949.

Best trial: 7. Best value: 0.648589:  20%|██        | 8/40 [00:14<00:41,  1.31s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:29,349] Trial 7 finished with value: 0.6485890652557319 and parameters: {'n_estimators': 81, 'max_depth': 4, 'learning_rate': 0.011662890273931383, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6332063738136893, 'gamma': 1.3567451588694794, 'reg_alpha': 4.143687545759647, 'reg_lambda': 1.7837666334679465}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  22%|██▎       | 9/40 [00:15<00:39,  1.26s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:30,505] Trial 8 finished with value: 0.5996472663139331 and parameters: {'n_estimators': 148, 'max_depth': 8, 'learning_rate': 0.016149614799999188, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 3.861223846483287, 'reg_lambda': 0.993578407670862}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  25%|██▌       | 10/40 [00:16<00:34,  1.14s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:31,379] Trial 9 finished with value: 0.4902998236331569 and parameters: {'n_estimators': 51, 'max_depth': 11, 'learning_rate': 0.11069143219393454, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8627622080115674, 'gamma': 0.3702232586704518, 'reg_alpha': 1.7923286427213632, 'reg_lambda': 0.5793452976256486}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  28%|██▊       | 11/40 [00:19<00:48,  1.69s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:34,312] Trial 10 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 381, 'max_depth': 3, 'learning_rate': 0.03504750508385009, 'subsample': 0.6071847502459279, 'colsample_bytree': 0.6522424049106386, 'gamma': 1.9014648012590532, 'reg_alpha': 4.854683575852504, 'reg_lambda': 3.3828618987138985}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  30%|███       | 12/40 [00:21<00:51,  1.83s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:36,477] Trial 11 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 382, 'max_depth': 3, 'learning_rate': 0.03747968471939845, 'subsample': 0.6046395533640769, 'colsample_bytree': 0.660246526995315, 'gamma': 1.9905558861290245, 'reg_alpha': 4.967337279906138, 'reg_lambda': 3.4055010480189933}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  32%|███▎      | 13/40 [00:24<00:58,  2.18s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:39,432] Trial 12 finished with value: 0.587742504409171 and parameters: {'n_estimators': 397, 'max_depth': 5, 'learning_rate': 0.026050431944310014, 'subsample': 0.6857486542395244, 'colsample_bytree': 0.6574321354126021, 'gamma': 1.9299645364103433, 'reg_alpha': 4.9847932584180255, 'reg_lambda': 3.2634060011249044}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  35%|███▌      | 14/40 [00:25<00:53,  2.06s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:41,227] Trial 13 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 315, 'max_depth': 5, 'learning_rate': 0.06707597765912318, 'subsample': 0.6049407588828821, 'colsample_bytree': 0.580770794183598, 'gamma': 2.5748520701047157, 'reg_alpha': 4.049830638482714, 'reg_lambda': 3.545998644876469}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  38%|███▊      | 15/40 [00:28<00:56,  2.25s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:43,912] Trial 14 finished with value: 0.5996472663139331 and parameters: {'n_estimators': 330, 'max_depth': 3, 'learning_rate': 0.028920703985722055, 'subsample': 0.7158449442367585, 'colsample_bytree': 0.7276301242970324, 'gamma': 1.51723150444279, 'reg_alpha': 4.324904285055905, 'reg_lambda': 1.7483218384404904}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  40%|████      | 16/40 [00:29<00:45,  1.89s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:44,981] Trial 15 finished with value: 0.5996472663139331 and parameters: {'n_estimators': 117, 'max_depth': 6, 'learning_rate': 0.06689802001564371, 'subsample': 0.6662225125541511, 'colsample_bytree': 0.8229562495609064, 'gamma': 2.939329982321473, 'reg_alpha': 4.47768117255101, 'reg_lambda': 0.04279269997456536}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  42%|████▎     | 17/40 [00:31<00:45,  1.96s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:47,104] Trial 16 finished with value: 0.5749559082892416 and parameters: {'n_estimators': 282, 'max_depth': 4, 'learning_rate': 0.016949840483162663, 'subsample': 0.759216484917874, 'colsample_bytree': 0.4093062291965364, 'gamma': 3.7245191375635525, 'reg_alpha': 2.224993919539197, 'reg_lambda': 2.7509005159154443}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  45%|████▌     | 18/40 [00:33<00:43,  1.98s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:49,111] Trial 17 finished with value: 0.6238977072310407 and parameters: {'n_estimators': 344, 'max_depth': 3, 'learning_rate': 0.11633185649566002, 'subsample': 0.6461443250339433, 'colsample_bytree': 0.6510638063380768, 'gamma': 1.4070712978947977, 'reg_alpha': 3.5969504337613936, 'reg_lambda': 3.8441724971783913}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  48%|████▊     | 19/40 [00:35<00:40,  1.93s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:50,927] Trial 18 finished with value: 0.5639329805996472 and parameters: {'n_estimators': 325, 'max_depth': 5, 'learning_rate': 0.13961565174538373, 'subsample': 0.6588917576760293, 'colsample_bytree': 0.5319375441588575, 'gamma': 1.2558371808135111, 'reg_alpha': 3.2754690436463525, 'reg_lambda': 4.081680645998777}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  50%|█████     | 20/40 [00:36<00:34,  1.72s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:52,148] Trial 19 finished with value: 0.5639329805996472 and parameters: {'n_estimators': 199, 'max_depth': 6, 'learning_rate': 0.16589322824275843, 'subsample': 0.7716886177898072, 'colsample_bytree': 0.6051199552909158, 'gamma': 2.4027299261311756, 'reg_alpha': 2.491167797628445, 'reg_lambda': 1.5630655156978412}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  52%|█████▎    | 21/40 [00:38<00:33,  1.75s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:53,960] Trial 20 finished with value: 0.5996472663139331 and parameters: {'n_estimators': 277, 'max_depth': 4, 'learning_rate': 0.05118602970431179, 'subsample': 0.7283963326407565, 'colsample_bytree': 0.8037416213556274, 'gamma': 1.514278238756251, 'reg_alpha': 3.6862820580610305, 'reg_lambda': 3.9931321835336355}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  55%|█████▌    | 22/40 [00:40<00:33,  1.86s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:56,106] Trial 21 finished with value: 0.6358024691358025 and parameters: {'n_estimators': 362, 'max_depth': 3, 'learning_rate': 0.08422524892255819, 'subsample': 0.6327524619699701, 'colsample_bytree': 0.6690158006976852, 'gamma': 1.9441383242522141, 'reg_alpha': 4.545951885780784, 'reg_lambda': 2.724580090225975}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  57%|█████▊    | 23/40 [00:42<00:31,  1.87s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:31:58,009] Trial 22 finished with value: 0.6353615520282186 and parameters: {'n_estimators': 353, 'max_depth': 3, 'learning_rate': 0.09712137282745187, 'subsample': 0.6452606057786048, 'colsample_bytree': 0.6807507893874093, 'gamma': 2.3482269715136708, 'reg_alpha': 4.370758204210595, 'reg_lambda': 4.911426758976196}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  60%|██████    | 24/40 [00:44<00:31,  1.94s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:00,087] Trial 23 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 349, 'max_depth': 4, 'learning_rate': 0.08848779239145749, 'subsample': 0.6369120198064522, 'colsample_bytree': 0.7065313323086824, 'gamma': 2.353154612091171, 'reg_alpha': 4.191626566547786, 'reg_lambda': 4.947306277660574}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  62%|██████▎   | 25/40 [00:46<00:27,  1.82s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:01,642] Trial 24 finished with value: 0.5996472663139331 and parameters: {'n_estimators': 301, 'max_depth': 6, 'learning_rate': 0.18366545090467862, 'subsample': 0.690503568630928, 'colsample_bytree': 0.6191631721858419, 'gamma': 2.887957332693476, 'reg_alpha': 4.505746513728619, 'reg_lambda': 2.89148186369253}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  65%|██████▌   | 26/40 [00:48<00:26,  1.88s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:03,664] Trial 25 finished with value: 0.6477072310405644 and parameters: {'n_estimators': 358, 'max_depth': 3, 'learning_rate': 0.07944650214735054, 'subsample': 0.7438294045145655, 'colsample_bytree': 0.6994056283878102, 'gamma': 3.7554412549120637, 'reg_alpha': 4.577929162096189, 'reg_lambda': 2.0928012442970565}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  68%|██████▊   | 27/40 [00:50<00:23,  1.81s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:05,324] Trial 26 finished with value: 0.6115520282186949 and parameters: {'n_estimators': 240, 'max_depth': 4, 'learning_rate': 0.0685796773521905, 'subsample': 0.8142258631292906, 'colsample_bytree': 0.5031761244678137, 'gamma': 3.7950092509846955, 'reg_alpha': 4.666116246876157, 'reg_lambda': 2.1341458618971947}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  70%|███████   | 28/40 [00:51<00:18,  1.58s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:06,358] Trial 27 finished with value: 0.6477072310405644 and parameters: {'n_estimators': 138, 'max_depth': 5, 'learning_rate': 0.05125270596973421, 'subsample': 0.7612728236643875, 'colsample_bytree': 0.7330634329620872, 'gamma': 4.142111736859842, 'reg_alpha': 3.916808985478343, 'reg_lambda': 1.3501722713178244}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  72%|███████▎  | 29/40 [00:52<00:15,  1.43s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:07,441] Trial 28 finished with value: 0.5987654320987654 and parameters: {'n_estimators': 124, 'max_depth': 7, 'learning_rate': 0.02244256364734941, 'subsample': 0.7655063569805187, 'colsample_bytree': 0.7349418978775545, 'gamma': 4.256118087626981, 'reg_alpha': 2.793507284209071, 'reg_lambda': 1.326839020178611}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  75%|███████▌  | 30/40 [00:53<00:13,  1.37s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:08,647] Trial 29 finished with value: 0.6353615520282186 and parameters: {'n_estimators': 175, 'max_depth': 5, 'learning_rate': 0.052723642774833865, 'subsample': 0.8522933552405686, 'colsample_bytree': 0.8029503987660609, 'gamma': 3.93716746198279, 'reg_alpha': 3.871892632882668, 'reg_lambda': 2.1831084501889966}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  78%|███████▊  | 31/40 [00:54<00:11,  1.25s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:09,624] Trial 30 finished with value: 0.5264550264550264 and parameters: {'n_estimators': 101, 'max_depth': 6, 'learning_rate': 0.012332025969238908, 'subsample': 0.8489817519564029, 'colsample_bytree': 0.8703434088338241, 'gamma': 3.4174793391618477, 'reg_alpha': 0.2137259003982086, 'reg_lambda': 1.3235859990233962}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  80%|████████  | 32/40 [00:55<00:08,  1.06s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:10,255] Trial 31 finished with value: 0.648148148148148 and parameters: {'n_estimators': 69, 'max_depth': 4, 'learning_rate': 0.085880073292235, 'subsample': 0.7432116298459912, 'colsample_bytree': 0.6886345974543144, 'gamma': 4.438179740235915, 'reg_alpha': 4.107519275241046, 'reg_lambda': 2.9057796944883103}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  82%|████████▎ | 33/40 [00:55<00:06,  1.11it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:10,768] Trial 32 finished with value: 0.6477072310405644 and parameters: {'n_estimators': 50, 'max_depth': 4, 'learning_rate': 0.07334582462059527, 'subsample': 0.7742692554592563, 'colsample_bytree': 0.7078531481166467, 'gamma': 4.924978134545473, 'reg_alpha': 4.0254788657948195, 'reg_lambda': 1.9794694416383023}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  85%|████████▌ | 34/40 [00:56<00:04,  1.21it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:11,443] Trial 33 finished with value: 0.6477072310405644 and parameters: {'n_estimators': 79, 'max_depth': 5, 'learning_rate': 0.043478764925367466, 'subsample': 0.7345677727342869, 'colsample_bytree': 0.7758642991470842, 'gamma': 4.295968741422586, 'reg_alpha': 3.587496564827491, 'reg_lambda': 2.327505765787483}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  88%|████████▊ | 35/40 [00:57<00:04,  1.11it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:12,511] Trial 34 finished with value: 0.5992063492063493 and parameters: {'n_estimators': 137, 'max_depth': 4, 'learning_rate': 0.14615748939744716, 'subsample': 0.823008048869822, 'colsample_bytree': 0.6277705102360067, 'gamma': 4.112933966344038, 'reg_alpha': 0.7650898848382357, 'reg_lambda': 1.521264508976068}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  90%|█████████ | 36/40 [00:58<00:04,  1.02s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:13,804] Trial 35 finished with value: 0.4902998236331569 and parameters: {'n_estimators': 167, 'max_depth': 5, 'learning_rate': 0.21021008007368455, 'subsample': 0.7923999351635298, 'colsample_bytree': 0.7564186808744613, 'gamma': 0.02729287688656612, 'reg_alpha': 3.3077028653890173, 'reg_lambda': 3.0472013537566784}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  92%|█████████▎| 37/40 [00:59<00:02,  1.07it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:14,550] Trial 36 finished with value: 0.648148148148148 and parameters: {'n_estimators': 70, 'max_depth': 10, 'learning_rate': 0.0581764151475933, 'subsample': 0.7442269879830082, 'colsample_bytree': 0.6940814487041325, 'gamma': 4.575001050268903, 'reg_alpha': 4.103607659113515, 'reg_lambda': 2.4546067764757216}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  95%|█████████▌| 38/40 [01:00<00:01,  1.15it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:15,271] Trial 37 finished with value: 0.6119929453262786 and parameters: {'n_estimators': 76, 'max_depth': 9, 'learning_rate': 0.06013918864441076, 'subsample': 0.7097072081372868, 'colsample_bytree': 0.586399442186891, 'gamma': 4.661230074006847, 'reg_alpha': 4.70704538538442, 'reg_lambda': 2.429281691922641}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589:  98%|█████████▊| 39/40 [01:00<00:00,  1.15it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3961897717.py:32: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),

[I 2026-04-09 23:32:16,125] Trial 38 finished with value: 0.6238977072310404 and parameters: {'n_estimators': 98, 'max_depth': 10, 'learning_rate': 0.10488693506565742, 'subsample': 0.7323172030968779, 'colsample_bytree': 0.6972822402840096, 'gamma': 4.595340531170809, 'reg_alpha': 2.980244102098565, 'reg_lambda': 1.8874068111119229}. Best is trial 7 with value: 0.6485890652557319.

Best trial: 7. Best value: 0.648589: 100%|██████████| 40/40 [01:02<00:00,  1.56s/it]

[I 2026-04-09 23:32:17,808] Trial 39 finished with value: 0.6234567901234568 and parameters: {'n_estimators': 197, 'max_depth': 12, 'learning_rate': 0.04322478701040103, 'subsample': 0.7452638432501364, 'colsample_bytree': 0.987907162839617, 'gamma': 3.518112587422709, 'reg_alpha': 4.251313643434011, 'reg_lambda': 2.5459838124191485}. Best is trial 7 with value: 0.6485890652557319.

Best CV mean High-recall: 0.6485890652557319
Best params:
  n_estimators: 81
  max_depth: 4
  learning_rate: 0.011662890273931383
  subsample: 0.7301321323053057
  colsample_bytree: 0.6332063738136893
  gamma: 1.3567451588694794
  reg_alpha: 4.143687545759647
  reg_lambda: 1.7837666334679465

FINAL Test Classification Report (labels in original names):
              precision    recall  f1-score   support

        High       0.16      0.60      0.26        20
         Low       0.50      0.77      0.60        65
      Medium       0.90      0.64      0.75       315

    accuracy                           0.66       400
   macro avg       0.52      0.67      0.54       400
weighted avg       0.80      0.66      0.70       400

Confusion Matrix (rows=true, cols=predicted, order = le.classes_):
[[ 12   0   8]
 [  0  50  15]
 [ 62  51 202]]

In [38]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# 1. Encode target labels (if not already numeric)
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

# 2. Compute class weights inversely proportional to class frequencies
classes, counts = np.unique(y_train_enc, return_counts=True)
class_weights = {cls: max(counts)/count for cls, count in zip(classes, counts)}
print("Class Weights:", class_weights)

# 3. Initialize XGBoost with weights
xgb_weighted = XGBClassifier(
    objective='multi:softmax',
    num_class=len(classes),
    eval_metric='mlogloss',
    random_state=42,
    n_estimators=105,
    max_depth=3,
    learning_rate=0.014843806162322944,
    subsample=0.7730982444721965,
    colsample_bytree=0.8509237341976973,
    gamma=4.134336554829186,
    reg_alpha=4.453508368364819,
    reg_lambda=2.616923339470738,
    n_jobs=-1
)

# 4. Fit model with per-sample weights
sample_weights = np.array([class_weights[y] for y in y_train_enc])
xgb_weighted.fit(X_train, y_train_enc, sample_weight=sample_weights)

# 5. Evaluate (baseline before Optuna tuning)
y_pred_enc = xgb_weighted.predict(X_test)
print("Baseline Class-weighted XGBoost (fixed params) - Classification Report")
print(classification_report(y_test_enc, y_pred_enc, target_names=le.classes_))
print("Confusion Matrix")
print(confusion_matrix(y_test_enc, y_pred_enc))

Class Weights: {0: 15.353658536585366, 1: 4.861003861003861, 2: 1.0}
Baseline Class-weighted XGBoost (fixed params) - Classification Report
              precision    recall  f1-score   support

        High       0.21      0.80      0.34        20
         Low       0.42      0.80      0.55        65
      Medium       0.92      0.58      0.71       315

    accuracy                           0.63       400
   macro avg       0.51      0.73      0.53       400
weighted avg       0.80      0.63      0.67       400

Confusion Matrix
[[ 16   0   4]
 [  0  52  13]
 [ 59  73 183]]

In [44]:
# Optuna tuning for class-weighted XGBoost (optimize macro-F1)
import optuna
from optuna.samplers import TPESampler
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# ----------------------
# Prepare encoded labels
# ----------------------
le = LabelEncoder()
le.fit(y_train)               # fit encoder on training labels
y_train_enc = le.transform(y_train)
y_test_enc  = le.transform(y_test)
n_classes = len(le.classes_)

# ----------------------
# Objective: maximize macro-F1
# ----------------------
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 400),
        'max_depth': trial.suggest_int('max_depth', 2, 12),
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'gamma': trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 5.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 5.0),
        # stable args:
        'use_label_encoder': False,
        'eval_metric': 'mlogloss',
        # set n_jobs=1 inside CV to avoid nested parallelism
    }

    cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    scores = []

    for train_idx, val_idx in cv.split(X_train, y_train_enc):
        X_t, X_v = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_t, y_v = y_train_enc[train_idx], y_train_enc[val_idx]

        # compute class weights from the fold's training data
        classes, counts = np.unique(y_t, return_counts=True)
        # simple inverse frequency scaling
        class_weight_map = {cls: float(max(counts) / cnt) for cls, cnt in zip(classes, counts)}
        sample_weights = np.array([class_weight_map[y] for y in y_t])

        # instantiate classifier with n_jobs=1 for CV
        model = XGBClassifier(**params, n_jobs=1, random_state=42)

        # fit with per-sample weights
        model.fit(X_t, y_t, sample_weight=sample_weights, verbose=False)

        y_pred = model.predict(X_v)
        scores.append(f1_score(y_v, y_pred, average='macro'))

    # return mean macro-F1 across folds
    return float(np.mean(scores))

# ----------------------
# Run Optuna study
# ----------------------
sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, study_name='xgb_class_weighted_macroF1')

# fewer trials to start; increase to 50-150 when comfortable
study.optimize(objective, n_trials=40, show_progress_bar=True)

print("Best CV macro-F1:", study.best_value)
print("Best params:")
for k, v in study.best_params.items():
    print(f"  {k}: {v}")

# ----------------------
# Train final model on full training set using class weights
# ----------------------
best = study.best_params.copy()
best.update({'use_label_encoder': False, 'eval_metric': 'mlogloss', 'random_state': 42})

# compute final sample weights from full training set
classes, counts = np.unique(y_train_enc, return_counts=True)
final_class_weight_map = {cls: float(max(counts)/cnt) for cls, cnt in zip(classes, counts)}
final_sample_weights = np.array([final_class_weight_map[y] for y in y_train_enc])

final_xgb = XGBClassifier(**best, n_jobs=-1)
final_xgb.fit(X_train, y_train_enc, sample_weight=final_sample_weights, verbose=False)

# Evaluate on untouched test set
y_test_pred_enc = final_xgb.predict(X_test)
y_test_pred = le.inverse_transform(y_test_pred_enc)
y_test_orig = y_test  # already readable labels

print("\nFINAL Test Classification Report (class-weighted XGB):")
print(classification_report(y_test_orig, y_test_pred, labels=le.classes_))
print("Confusion Matrix (rows=true, cols=pred):")
print(confusion_matrix(y_test_orig, y_test_pred, labels=le.classes_))

[I 2026-04-09 23:37:09,510] A new study created in memory with name: xgb_class_weighted_macroF1
  0%|          | 0/40 [00:00<?, ?it/s]

C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),
Best trial: 0. Best value: 0.708262:   2%|▎         | 1/40 [00:01<00:43,  1.11s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:10,605] Trial 0 finished with value: 0.7082617917262457 and parameters: {'n_estimators': 181, 'max_depth': 12, 'learning_rate': 0.06504856968981275, 'subsample': 0.8394633936788146, 'colsample_bytree': 0.4936111842654619, 'gamma': 0.7799726016810132, 'reg_alpha': 0.2904180608409973, 'reg_lambda': 4.330880728874676}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:   5%|▌         | 2/40 [00:04<01:28,  2.34s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:13,819] Trial 1 finished with value: 0.6540759814438694 and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.001124579825911934, 'subsample': 0.9879639408647978, 'colsample_bytree': 0.899465584480253, 'gamma': 1.0616955533913808, 'reg_alpha': 0.9091248360355031, 'reg_lambda': 0.9170225492671691}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:   8%|▊         | 3/40 [00:05<01:11,  1.93s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:15,271] Trial 2 finished with value: 0.6902295524212589 and parameters: {'n_estimators': 156, 'max_depth': 7, 'learning_rate': 0.01174843954800703, 'subsample': 0.7164916560792167, 'colsample_bytree': 0.7671117368334277, 'gamma': 0.6974693032602092, 'reg_alpha': 1.4607232426760908, 'reg_lambda': 1.8318092164684585}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  10%|█         | 4/40 [00:08<01:18,  2.19s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:17,836] Trial 3 finished with value: 0.6850334876985409 and parameters: {'n_estimators': 210, 'max_depth': 10, 'learning_rate': 0.003123317753376431, 'subsample': 0.8056937753654446, 'colsample_bytree': 0.7554487413172255, 'gamma': 0.23225206359998862, 'reg_alpha': 3.0377242595071916, 'reg_lambda': 0.8526206184364576}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  12%|█▎        | 5/40 [00:08<00:57,  1.64s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:18,505] Trial 4 finished with value: 0.692576308810711 and parameters: {'n_estimators': 72, 'max_depth': 12, 'learning_rate': 0.24659691172104828, 'subsample': 0.9233589392465844, 'colsample_bytree': 0.5827682615040224, 'gamma': 0.48836057003191935, 'reg_alpha': 3.4211651325607844, 'reg_lambda': 2.2007624686980067}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  15%|█▌        | 6/40 [00:09<00:47,  1.39s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:19,412] Trial 5 finished with value: 0.6491216381182894 and parameters: {'n_estimators': 92, 'max_depth': 7, 'learning_rate': 0.0012167028814593455, 'subsample': 0.9637281608315128, 'colsample_bytree': 0.5552679889600102, 'gamma': 3.31261142176991, 'reg_alpha': 1.5585553804470549, 'reg_lambda': 2.600340105889054}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  18%|█▊        | 7/40 [00:10<00:41,  1.26s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:20,406] Trial 6 finished with value: 0.6729455790443942 and parameters: {'n_estimators': 241, 'max_depth': 4, 'learning_rate': 0.25221951700214285, 'subsample': 0.9100531293444458, 'colsample_bytree': 0.9636993649385135, 'gamma': 4.474136752138244, 'reg_alpha': 2.9894998940554256, 'reg_lambda': 4.609371175115584}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  20%|██        | 8/40 [00:11<00:35,  1.11s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:21,204] Trial 7 finished with value: 0.5855691929987382 and parameters: {'n_estimators': 81, 'max_depth': 4, 'learning_rate': 0.001294295611551122, 'subsample': 0.7301321323053057, 'colsample_bytree': 0.6332063738136893, 'gamma': 1.3567451588694794, 'reg_alpha': 4.143687545759647, 'reg_lambda': 1.7837666334679465}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  22%|██▎       | 9/40 [00:13<00:38,  1.24s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:22,705] Trial 8 finished with value: 0.6092902721883291 and parameters: {'n_estimators': 148, 'max_depth': 7, 'learning_rate': 0.0022340165853190056, 'subsample': 0.9208787923016158, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 3.861223846483287, 'reg_lambda': 0.993578407670862}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  25%|██▌       | 10/40 [00:14<00:33,  1.11s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:23,526] Trial 9 finished with value: 0.6866328209171698 and parameters: {'n_estimators': 51, 'max_depth': 10, 'learning_rate': 0.0563600475052774, 'subsample': 0.8916028672163949, 'colsample_bytree': 0.8627622080115674, 'gamma': 0.3702232586704518, 'reg_alpha': 1.7923286427213632, 'reg_lambda': 0.5793452976256486}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  28%|██▊       | 11/40 [00:15<00:34,  1.19s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:24,889] Trial 10 finished with value: 0.6797915489410337 and parameters: {'n_estimators': 364, 'max_depth': 2, 'learning_rate': 0.04220565240590451, 'subsample': 0.6071847502459279, 'colsample_bytree': 0.4092206423968626, 'gamma': 2.1904046373091504, 'reg_alpha': 0.0757211855137844, 'reg_lambda': 4.880699499289976}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 0. Best value: 0.708262:  30%|███       | 12/40 [00:16<00:31,  1.11s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:25,837] Trial 11 finished with value: 0.6827847587605277 and parameters: {'n_estimators': 325, 'max_depth': 12, 'learning_rate': 0.29246630132511764, 'subsample': 0.8369993090060779, 'colsample_bytree': 0.5400682861238154, 'gamma': 1.9753377685495535, 'reg_alpha': 4.744701625551478, 'reg_lambda': 3.612146714899965}. Best is trial 0 with value: 0.7082617917262457.

Best trial: 12. Best value: 0.713532:  32%|███▎      | 13/40 [00:17<00:31,  1.15s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:27,084] Trial 12 finished with value: 0.713531562691804 and parameters: {'n_estimators': 153, 'max_depth': 12, 'learning_rate': 0.10066481531401737, 'subsample': 0.8566880772987617, 'colsample_bytree': 0.5567951578819594, 'gamma': 0.04655577784569398, 'reg_alpha': 2.343526094439211, 'reg_lambda': 3.2634060011249044}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  35%|███▌      | 14/40 [00:19<00:32,  1.26s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:28,600] Trial 13 finished with value: 0.6418028293379247 and parameters: {'n_estimators': 172, 'max_depth': 12, 'learning_rate': 0.0727097883234817, 'subsample': 0.7475640316733063, 'colsample_bytree': 0.47893707996091966, 'gamma': 0.01573136739885428, 'reg_alpha': 0.0435496921427041, 'reg_lambda': 3.7736689845475873}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  38%|███▊      | 15/40 [00:20<00:29,  1.19s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:29,617] Trial 14 finished with value: 0.6793440763776127 and parameters: {'n_estimators': 128, 'max_depth': 9, 'learning_rate': 0.01703494728309752, 'subsample': 0.8578694741072341, 'colsample_bytree': 0.6740462231777771, 'gamma': 1.51723150444279, 'reg_alpha': 2.31057379200564, 'reg_lambda': 3.408415413612532}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  40%|████      | 16/40 [00:20<00:25,  1.05s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:30,334] Trial 15 finished with value: 0.7027826363131915 and parameters: {'n_estimators': 203, 'max_depth': 10, 'learning_rate': 0.10842578390687244, 'subsample': 0.7885344267580748, 'colsample_bytree': 0.48128215947448744, 'gamma': 2.967945385475436, 'reg_alpha': 0.7298898221377486, 'reg_lambda': 3.0130840175825337}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  42%|████▎     | 17/40 [00:22<00:27,  1.22s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:31,941] Trial 16 finished with value: 0.6972977298154198 and parameters: {'n_estimators': 282, 'max_depth': 11, 'learning_rate': 0.029947479818081248, 'subsample': 0.8439606469298555, 'colsample_bytree': 0.6238647943500348, 'gamma': 1.0573711172583258, 'reg_alpha': 2.2300471064129566, 'reg_lambda': 4.138936297287702}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  45%|████▌     | 18/40 [00:22<00:22,  1.01s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:32,467] Trial 17 finished with value: 0.7016709209630371 and parameters: {'n_estimators': 127, 'max_depth': 5, 'learning_rate': 0.1208126868376585, 'subsample': 0.6697274314999843, 'colsample_bytree': 0.5224466163605349, 'gamma': 3.634823758940222, 'reg_alpha': 0.8084045256389525, 'reg_lambda': 4.2125827933612285}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  48%|████▊     | 19/40 [00:24<00:24,  1.15s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:33,953] Trial 18 finished with value: 0.661953671044119 and parameters: {'n_estimators': 194, 'max_depth': 9, 'learning_rate': 0.009576614089790204, 'subsample': 0.8029967056557425, 'colsample_bytree': 0.7240570120681563, 'gamma': 1.8024634022390282, 'reg_alpha': 4.964979672616705, 'reg_lambda': 3.010292280601603}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  50%|█████     | 20/40 [00:25<00:23,  1.17s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:35,163] Trial 19 finished with value: 0.6839958223933106 and parameters: {'n_estimators': 286, 'max_depth': 8, 'learning_rate': 0.02675016510189371, 'subsample': 0.7695956616104436, 'colsample_bytree': 0.4098863946600695, 'gamma': 2.507285077111833, 'reg_alpha': 2.7269957832354033, 'reg_lambda': 4.078649186547714}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  52%|█████▎    | 21/40 [00:26<00:19,  1.00s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:35,770] Trial 20 finished with value: 0.7004631570108771 and parameters: {'n_estimators': 107, 'max_depth': 11, 'learning_rate': 0.110335181350503, 'subsample': 0.8693386818617739, 'colsample_bytree': 0.644684035845743, 'gamma': 0.861160334752887, 'reg_alpha': 1.9365811801792985, 'reg_lambda': 3.1631519638115915}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  55%|█████▌    | 22/40 [00:27<00:17,  1.02it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:36,717] Trial 21 finished with value: 0.6917519341922338 and parameters: {'n_estimators': 189, 'max_depth': 11, 'learning_rate': 0.12411475072587193, 'subsample': 0.7833146591802602, 'colsample_bytree': 0.4883568158000779, 'gamma': 2.823652012655651, 'reg_alpha': 0.6724173620052483, 'reg_lambda': 2.8065220119614347}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  57%|█████▊    | 23/40 [00:28<00:16,  1.06it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:37,583] Trial 22 finished with value: 0.6904733403970099 and parameters: {'n_estimators': 230, 'max_depth': 10, 'learning_rate': 0.08129542473603392, 'subsample': 0.8168210886828632, 'colsample_bytree': 0.47805016174736165, 'gamma': 3.2149467463689354, 'reg_alpha': 1.2387506558347754, 'reg_lambda': 2.2991898855193944}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  60%|██████    | 24/40 [00:28<00:14,  1.10it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:38,399] Trial 23 finished with value: 0.6935754388995408 and parameters: {'n_estimators': 176, 'max_depth': 12, 'learning_rate': 0.15652049864355208, 'subsample': 0.6945030754047237, 'colsample_bytree': 0.5994499377398806, 'gamma': 3.9623716367291486, 'reg_alpha': 0.43981942047821176, 'reg_lambda': 3.2799223373332302}. Best is trial 12 with value: 0.713531562691804.

Best trial: 12. Best value: 0.713532:  62%|██████▎   | 25/40 [00:29<00:14,  1.05it/s]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:39,457] Trial 24 finished with value: 0.690533692465562 and parameters: {'n_estimators': 209, 'max_depth': 11, 'learning_rate': 0.04322533042504333, 'subsample': 0.8802341334492112, 'colsample_bytree': 0.5169151862211332, 'gamma': 2.7007699705170394, 'reg_alpha': 1.1520142103431266, 'reg_lambda': 4.522457264033607}. Best is trial 12 with value: 0.713531562691804.

Best trial: 25. Best value: 0.719511:  65%|██████▌   | 26/40 [00:31<00:14,  1.02s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:40,618] Trial 25 finished with value: 0.7195106843953635 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.16918550254611062, 'subsample': 0.765836702637975, 'colsample_bytree': 0.4462693017157447, 'gamma': 1.504076411214792, 'reg_alpha': 0.5277880540484166, 'reg_lambda': 3.7963570997509537}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 25. Best value: 0.719511:  68%|██████▊   | 27/40 [00:32<00:13,  1.07s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:41,832] Trial 26 finished with value: 0.713377484370754 and parameters: {'n_estimators': 389, 'max_depth': 12, 'learning_rate': 0.18364730647710378, 'subsample': 0.7649011048051568, 'colsample_bytree': 0.571849675833678, 'gamma': 1.4372129508305722, 'reg_alpha': 0.22102917393250898, 'reg_lambda': 4.996627073707741}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 25. Best value: 0.719511:  70%|███████   | 28/40 [00:33<00:14,  1.19s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:43,280] Trial 27 finished with value: 0.7052454860155839 and parameters: {'n_estimators': 397, 'max_depth': 11, 'learning_rate': 0.18038896909908636, 'subsample': 0.6655232394152557, 'colsample_bytree': 0.5726111934192712, 'gamma': 1.4635679205345233, 'reg_alpha': 0.41440331074275605, 'reg_lambda': 4.910657193551222}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 25. Best value: 0.719511:  72%|███████▎  | 29/40 [00:35<00:13,  1.23s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:44,592] Trial 28 finished with value: 0.7020727569230468 and parameters: {'n_estimators': 397, 'max_depth': 8, 'learning_rate': 0.19266180757352105, 'subsample': 0.7638906473819108, 'colsample_bytree': 0.677260634554755, 'gamma': 2.3261270998049848, 'reg_alpha': 1.2489860320325465, 'reg_lambda': 3.767047301677018}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 25. Best value: 0.719511:  75%|███████▌  | 30/40 [00:38<00:17,  1.73s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:47,513] Trial 29 finished with value: 0.6777083057098524 and parameters: {'n_estimators': 351, 'max_depth': 12, 'learning_rate': 0.00591011976296499, 'subsample': 0.8301191845587425, 'colsample_bytree': 0.4306867086130053, 'gamma': 1.8607765228464794, 'reg_alpha': 0.3129314589586414, 'reg_lambda': 3.9215428481035177}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 25. Best value: 0.719511:  78%|███████▊  | 31/40 [00:39<00:15,  1.67s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:49,050] Trial 30 finished with value: 0.7051534247550685 and parameters: {'n_estimators': 317, 'max_depth': 6, 'learning_rate': 0.07321723417028221, 'subsample': 0.7452490250707723, 'colsample_bytree': 0.8045259699072966, 'gamma': 1.2538792048714942, 'reg_alpha': 1.9113130844777728, 'reg_lambda': 4.340757465351458}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 25. Best value: 0.719511:  80%|████████  | 32/40 [00:41<00:12,  1.61s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:50,517] Trial 31 finished with value: 0.6768998377541923 and parameters: {'n_estimators': 368, 'max_depth': 9, 'learning_rate': 0.16603916801451502, 'subsample': 0.9655051136093007, 'colsample_bytree': 0.4556042778778444, 'gamma': 0.7516204052280621, 'reg_alpha': 0.9495559795826118, 'reg_lambda': 4.625580919164516}. Best is trial 25 with value: 0.7195106843953635.

Best trial: 32. Best value: 0.722331:  82%|████████▎ | 33/40 [00:42<00:10,  1.55s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:51,930] Trial 32 finished with value: 0.7223307017879933 and parameters: {'n_estimators': 272, 'max_depth': 12, 'learning_rate': 0.0891879979030594, 'subsample': 0.7012866277412377, 'colsample_bytree': 0.5316068128421201, 'gamma': 1.068501671883885, 'reg_alpha': 0.35571336905345036, 'reg_lambda': 4.9617905262303115}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331:  85%|████████▌ | 34/40 [00:44<00:10,  1.67s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:53,871] Trial 33 finished with value: 0.7105182171196515 and parameters: {'n_estimators': 319, 'max_depth': 12, 'learning_rate': 0.05009413897941797, 'subsample': 0.7106585272668525, 'colsample_bytree': 0.5315221205727245, 'gamma': 1.0451520119919802, 'reg_alpha': 0.5285098654852293, 'reg_lambda': 4.9295638526379815}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331:  88%|████████▊ | 35/40 [00:46<00:09,  1.80s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:55,985] Trial 34 finished with value: 0.6870132820131895 and parameters: {'n_estimators': 270, 'max_depth': 11, 'learning_rate': 0.08981476672649959, 'subsample': 0.6393062045165578, 'colsample_bytree': 0.5994921315657034, 'gamma': 0.021005574271798055, 'reg_alpha': 0.05027652864733578, 'reg_lambda': 4.497719786378529}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331:  90%|█████████ | 36/40 [00:48<00:07,  1.90s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:58,111] Trial 35 finished with value: 0.7069127086991362 and parameters: {'n_estimators': 377, 'max_depth': 10, 'learning_rate': 0.03074073004550703, 'subsample': 0.6876417350588805, 'colsample_bytree': 0.5583856733152482, 'gamma': 0.5795162285041164, 'reg_alpha': 1.490992410227844, 'reg_lambda': 3.538415059718254}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331:  92%|█████████▎| 37/40 [00:49<00:04,  1.64s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:37:59,152] Trial 36 finished with value: 0.6993464948951363 and parameters: {'n_estimators': 345, 'max_depth': 12, 'learning_rate': 0.22354082687541488, 'subsample': 0.7253281535851964, 'colsample_bytree': 0.5024467094387719, 'gamma': 1.690387023727145, 'reg_alpha': 0.9973677577523306, 'reg_lambda': 3.974746065106717}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331:  95%|█████████▌| 38/40 [00:50<00:03,  1.52s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:38:00,380] Trial 37 finished with value: 0.7079511717903452 and parameters: {'n_estimators': 256, 'max_depth': 11, 'learning_rate': 0.13582223319946057, 'subsample': 0.7546800649864809, 'colsample_bytree': 0.7239805276342184, 'gamma': 0.88123387456458, 'reg_alpha': 3.3064091089796817, 'reg_lambda': 2.6332441284248995}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331:  98%|█████████▊| 39/40 [00:52<00:01,  1.43s/it]C:\Users\Acer\AppData\Local\Temp\ipykernel_22924\3887491615.py:26: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.3),

[I 2026-04-09 23:38:01,582] Trial 38 finished with value: 0.7004748393560715 and parameters: {'n_estimators': 299, 'max_depth': 8, 'learning_rate': 0.09235930731283669, 'subsample': 0.7822763706887431, 'colsample_bytree': 0.6036685072791683, 'gamma': 2.1604618811844425, 'reg_alpha': 0.2637800420157097, 'reg_lambda': 4.737939640285915}. Best is trial 32 with value: 0.7223307017879933.

Best trial: 32. Best value: 0.722331: 100%|██████████| 40/40 [00:53<00:00,  1.34s/it]

[I 2026-04-09 23:38:03,111] Trial 39 finished with value: 0.7181749203837389 and parameters: {'n_estimators': 342, 'max_depth': 10, 'learning_rate': 0.23669906019907733, 'subsample': 0.8140972951144148, 'colsample_bytree': 0.987907162839617, 'gamma': 0.3884593998243786, 'reg_alpha': 4.251313643434011, 'reg_lambda': 1.7335263513565262}. Best is trial 32 with value: 0.7223307017879933.
Best CV macro-F1: 0.7223307017879933
Best params:
  n_estimators: 272
  max_depth: 12
  learning_rate: 0.0891879979030594
  subsample: 0.7012866277412377
  colsample_bytree: 0.5316068128421201
  gamma: 1.068501671883885
  reg_alpha: 0.35571336905345036
  reg_lambda: 4.9617905262303115

FINAL Test Classification Report (class-weighted XGB):
              precision    recall  f1-score   support

        High       0.53      0.45      0.49        20
         Low       0.71      0.77      0.74        65
      Medium       0.92      0.91      0.91       315

    accuracy                           0.86       400
   macro avg       0.72      0.71      0.71       400
weighted avg       0.86      0.86      0.86       400

Confusion Matrix (rows=true, cols=pred):
[[  9   0  11]
 [  0  50  15]
 [  8  20 287]]

In [45]:
from sklearn.metrics import accuracy_score

# Recompute from the final class-weighted XGBoost model to avoid stale in-memory variables.
if all(name in globals() for name in ['final_xgb', 'X_test', 'y_test_enc']):
    y_pred_final = final_xgb.predict(X_test)
    final_acc = accuracy_score(y_test_enc, y_pred_final)
    print(f"Latest final accuracy (recomputed from final_xgb): {final_acc:.2f}")
else:
    print("Final model/test variables are not in memory. Run the final class-weighted XGBoost cell first.")

Latest final accuracy (recomputed from final_xgb): 0.86

## Winner: Optuna-Tuned Class-weighted XGBoost

![Final class-weighted XGBoost accuracy 0.86](assets/final_accuracy_086.png)

Latest verified final test accuracy from the current run: **0.86**

## Save the model as a .pkl file

In [41]:
import joblib

joblib.dump(model,'model_xgb_new.pkl')

print("Model saved successfully as 'model_xgb_new.pkl'")

Model saved successfully as 'model_xgb_new.pkl'